
name: Build and Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: pdn
    strategy:
      matrix:
        include:
          - TEST_NAME: "Latest v2"
            AWS_CLI_VERSION: "2"
            node-version:  14.x
            bucket-name: cucos-fc
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: npm run build -c=production --prod --if-present
    - name: Test ${{ matrix.TEST_NAME }}
      id: install-aws-cli
      uses: unfor19/install-aws-cli-action@master
      with:
        version: ${{ matrix.AWS_CLI_VERSION }}
    - run: aws --version
      shell: bash
    - name: Configure awscli
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY 
        aws configure set region us-east-1
    - name: Uploading of files to Amazon S3
      run: |
        cd dist/cucos-fc-news
        aws s3 cp ./ s3://${{ matrix.bucket-name }} --region=us-east-1  --recursive
